repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: detect-private-key
  - id: check-json
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-yaml
    args:
     - --unsafe

- repo: https://github.com/k8s-at-home/sops-pre-commit
  rev: v2.0.3
  hooks:
  - id: forbid-secrets

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.254
  hooks:
  - id: ruff
    args:
    - --fix
- repo: https://github.com/hadolint/hadolint
  rev: "v2.10.0"
  hooks:
    - id: hadolint-docker
      args:
        - --ignore
        - DL4006
        - --ignore
        - DL3015
